package net.fellter.vanillablocksplus.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.fellter.vanillablocksplus.block.ModBlocks;
import net.minecraft.block.Block;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.BlockTags;
import net.minecraft.registry.tag.TagKey;
import net.minecraft.util.Identifier;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends FabricTagProvider.BlockTagProvider {
     public ModBlockTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
        super(output, registriesFuture);
    }

    @Override
    protected void configure(RegistryWrapper.WrapperLookup arg) {

         getOrCreateTagBuilder(BlockTags.SHOVEL_MINEABLE)
                 //packed mud
                 .add(ModBlocks.PACKED_MUD_STAIRS)
                 .add(ModBlocks.PACKED_MUD_SLAB)
                 .add(ModBlocks.PACKED_MUD_WALL)
                 .add(ModBlocks.PACKED_MUD_DOOR)
                 .add(ModBlocks.PACKED_MUD_TRAPDOOR)
                 .add(ModBlocks.PACKED_MUD_FENCE_GATE)
                 .add(ModBlocks.PACKED_MUD_FENCE)
                 .add(ModBlocks.PACKED_MUD_BUTTON)
                 .add(ModBlocks.PACKED_MUD_PRESSURE_PLATE);

        getOrCreateTagBuilder(BlockTags.PICKAXE_MINEABLE)
                //stone
                .add(ModBlocks.STONE_DOOR)
                .add(ModBlocks.STONE_TRAPDOOR)
                .add(ModBlocks.STONE_FENCE_GATE)
                .add(ModBlocks.STONE_FENCE)
                //cobblestone
                .add(ModBlocks.COBBLESTONE_DOOR)
                .add(ModBlocks.COBBLESTONE_TRAPDOOR)
                .add(ModBlocks.COBBLESTONE_FENCE_GATE)
                .add(ModBlocks.COBBLESTONE_FENCE)
                //mossy cobblestone
                .add(ModBlocks.MOSSY_COBBLESTONE_DOOR)
                .add(ModBlocks.MOSSY_COBBLESTONE_TRAPDOOR)
                .add(ModBlocks.MOSSY_COBBLESTONE_FENCE_GATE)
                .add(ModBlocks.MOSSY_COBBLESTONE_FENCE)
                .add(ModBlocks.MOSSY_COBBLESTONE_BUTTON)
                .add(ModBlocks.MOSSY_COBBLESTONE_PRESSURE_PLATE)
                //smooth stone
                .add(ModBlocks.SMOOTH_STONE_STAIRS)
                .add(ModBlocks.SMOOTH_STONE_DOOR)
                .add(ModBlocks.SMOOTH_STONE_TRAPDOOR)
                .add(ModBlocks.SMOOTH_STONE_FENCE_GATE)
                .add(ModBlocks.SMOOTH_STONE_FENCE)
                .add(ModBlocks.SMOOTH_STONE_BUTTON)
                .add(ModBlocks.SMOOTH_STONE_PRESSURE_PLATE)
                .add(ModBlocks.SMOOTH_STONE_WALL)
                //stone bricks
                .add(ModBlocks.STONE_BRICKS_DOOR)
                .add(ModBlocks.STONE_BRICKS_TRAPDOOR)
                .add(ModBlocks.STONE_BRICKS_FENCE_GATE)
                .add(ModBlocks.STONE_BRICKS_FENCE)
                .add(ModBlocks.STONE_BRICKS_BUTTON)
                .add(ModBlocks.STONE_BRICKS_PRESSURE_PLATE)
                //cracked stone bricks
                .add(ModBlocks.CRACKED_STONE_BRICKS_STAIRS)
                .add(ModBlocks.CRACKED_STONE_BRICKS_SLAB)
                .add(ModBlocks.CRACKED_STONE_BRICKS_WALL)
                .add(ModBlocks.CRACKED_STONE_BRICKS_DOOR)
                .add(ModBlocks.CRACKED_STONE_BRICKS_TRAPDOOR)
                .add(ModBlocks.CRACKED_STONE_BRICKS_FENCE_GATE)
                .add(ModBlocks.CRACKED_STONE_BRICKS_FENCE)
                .add(ModBlocks.CRACKED_STONE_BRICKS_BUTTON)
                .add(ModBlocks.CRACKED_STONE_BRICKS_PRESSURE_PLATE)
                //granite
                .add(ModBlocks.GRANITE_DOOR)
                .add(ModBlocks.GRANITE_TRAPDOOR)
                .add(ModBlocks.GRANITE_FENCE_GATE)
                .add(ModBlocks.GRANITE_FENCE)
                .add(ModBlocks.GRANITE_BUTTON)
                .add(ModBlocks.GRANITE_PRESSURE_PLATE)
                //polished granite
                .add(ModBlocks.POLISHED_GRANITE_DOOR)
                .add(ModBlocks.POLISHED_GRANITE_TRAPDOOR)
                .add(ModBlocks.POLISHED_GRANITE_FENCE_GATE)
                .add(ModBlocks.POLISHED_GRANITE_FENCE)
                .add(ModBlocks.POLISHED_GRANITE_BUTTON)
                .add(ModBlocks.POLISHED_GRANITE_PRESSURE_PLATE)
                .add(ModBlocks.POLISHED_GRANITE_WALL)
                //diorite
                .add(ModBlocks.DIORITE_DOOR)
                .add(ModBlocks.DIORITE_TRAPDOOR)
                .add(ModBlocks.DIORITE_FENCE_GATE)
                .add(ModBlocks.DIORITE_FENCE)
                .add(ModBlocks.DIORITE_BUTTON)
                .add(ModBlocks.DIORITE_PRESSURE_PLATE)
                //polished diorite
                .add(ModBlocks.POLISHED_DIORITE_DOOR)
                .add(ModBlocks.POLISHED_DIORITE_TRAPDOOR)
                .add(ModBlocks.POLISHED_DIORITE_FENCE_GATE)
                .add(ModBlocks.POLISHED_DIORITE_FENCE)
                .add(ModBlocks.POLISHED_DIORITE_BUTTON)
                .add(ModBlocks.POLISHED_DIORITE_PRESSURE_PLATE)
                .add(ModBlocks.POLISHED_DIORITE_WALL)
                //andesite
                .add(ModBlocks.ANDESITE_DOOR)
                .add(ModBlocks.ANDESITE_TRAPDOOR)
                .add(ModBlocks.ANDESITE_FENCE_GATE)
                .add(ModBlocks.ANDESITE_FENCE)
                .add(ModBlocks.ANDESITE_BUTTON)
                .add(ModBlocks.ANDESITE_PRESSURE_PLATE)
                //polished andesite
                .add(ModBlocks.POLISHED_ANDESITE_DOOR)
                .add(ModBlocks.POLISHED_ANDESITE_TRAPDOOR)
                .add(ModBlocks.POLISHED_ANDESITE_FENCE_GATE)
                .add(ModBlocks.POLISHED_ANDESITE_FENCE)
                .add(ModBlocks.POLISHED_ANDESITE_BUTTON)
                .add(ModBlocks.POLISHED_ANDESITE_PRESSURE_PLATE)
                .add(ModBlocks.POLISHED_ANDESITE_WALL)
                //deepslate
                .add(ModBlocks.DEEPSLATE_STAIRS)
                .add(ModBlocks.DEEPSLATE_SLAB)
                .add(ModBlocks.DEEPSLATE_WALL)
                .add(ModBlocks.DEEPSLATE_DOOR)
                .add(ModBlocks.DEEPSLATE_TRAPDOOR)
                .add(ModBlocks.DEEPSLATE_FENCE_GATE)
                .add(ModBlocks.DEEPSLATE_FENCE)
                .add(ModBlocks.DEEPSLATE_BUTTON)
                .add(ModBlocks.DEEPSLATE_PRESSURE_PLATE)
                //cobbled deepslate
                .add(ModBlocks.COBBLED_DEEPSLATE_DOOR)
                .add(ModBlocks.COBBLED_DEEPSLATE_TRAPDOOR)
                .add(ModBlocks.COBBLED_DEEPSLATE_FENCE_GATE)
                .add(ModBlocks.COBBLED_DEEPSLATE_FENCE)
                .add(ModBlocks.COBBLED_DEEPSLATE_BUTTON)
                .add(ModBlocks.COBBLED_DEEPSLATE_PRESSURE_PLATE)
                //deepslate
                .add(ModBlocks.CHISELED_DEEPSLATE_STAIRS)
                .add(ModBlocks.CHISELED_DEEPSLATE_SLAB)
                .add(ModBlocks.CHISELED_DEEPSLATE_WALL)
                .add(ModBlocks.CHISELED_DEEPSLATE_DOOR)
                .add(ModBlocks.CHISELED_DEEPSLATE_TRAPDOOR)
                .add(ModBlocks.CHISELED_DEEPSLATE_FENCE_GATE)
                .add(ModBlocks.CHISELED_DEEPSLATE_FENCE)
                .add(ModBlocks.CHISELED_DEEPSLATE_BUTTON)
                .add(ModBlocks.CHISELED_DEEPSLATE_PRESSURE_PLATE)
                //polished deepslate
                .add(ModBlocks.POLISHED_DEEPSLATE_DOOR)
                .add(ModBlocks.POLISHED_DEEPSLATE_TRAPDOOR)
                .add(ModBlocks.POLISHED_DEEPSLATE_FENCE_GATE)
                .add(ModBlocks.POLISHED_DEEPSLATE_FENCE)
                .add(ModBlocks.POLISHED_DEEPSLATE_BUTTON)
                .add(ModBlocks.POLISHED_DEEPSLATE_PRESSURE_PLATE)
                //deepslate bricks
                .add(ModBlocks.DEEPSLATE_BRICKS_DOOR)
                .add(ModBlocks.DEEPSLATE_BRICKS_TRAPDOOR)
                .add(ModBlocks.DEEPSLATE_BRICKS_FENCE_GATE)
                .add(ModBlocks.DEEPSLATE_BRICKS_FENCE)
                .add(ModBlocks.DEEPSLATE_BRICKS_BUTTON)
                .add(ModBlocks.DEEPSLATE_BRICKS_PRESSURE_PLATE)
                //cracked deepslate bricks
                .add(ModBlocks.CRACKED_DEEPSLATE_BRICKS_STAIRS)
                .add(ModBlocks.CRACKED_DEEPSLATE_BRICKS_SLAB)
                .add(ModBlocks.CRACKED_DEEPSLATE_BRICKS_WALL)
                .add(ModBlocks.CRACKED_DEEPSLATE_BRICKS_DOOR)
                .add(ModBlocks.CRACKED_DEEPSLATE_BRICKS_TRAPDOOR)
                .add(ModBlocks.CRACKED_DEEPSLATE_BRICKS_FENCE_GATE)
                .add(ModBlocks.CRACKED_DEEPSLATE_BRICKS_FENCE)
                .add(ModBlocks.CRACKED_DEEPSLATE_BRICKS_BUTTON)
                .add(ModBlocks.CRACKED_DEEPSLATE_BRICKS_PRESSURE_PLATE)
                //deepslate tiles
                .add(ModBlocks.DEEPSLATE_TILES_DOOR)
                .add(ModBlocks.DEEPSLATE_TILES_TRAPDOOR)
                .add(ModBlocks.DEEPSLATE_TILES_FENCE_GATE)
                .add(ModBlocks.DEEPSLATE_TILES_FENCE)
                .add(ModBlocks.DEEPSLATE_TILES_BUTTON)
                .add(ModBlocks.DEEPSLATE_TILES_PRESSURE_PLATE)
                //cracked deepslate tiles
                .add(ModBlocks.CRACKED_DEEPSLATE_TILES_STAIRS)
                .add(ModBlocks.CRACKED_DEEPSLATE_TILES_SLAB)
                .add(ModBlocks.CRACKED_DEEPSLATE_TILES_WALL)
                .add(ModBlocks.CRACKED_DEEPSLATE_TILES_DOOR)
                .add(ModBlocks.CRACKED_DEEPSLATE_TILES_TRAPDOOR)
                .add(ModBlocks.CRACKED_DEEPSLATE_TILES_FENCE_GATE)
                .add(ModBlocks.CRACKED_DEEPSLATE_TILES_FENCE)
                .add(ModBlocks.CRACKED_DEEPSLATE_TILES_BUTTON)
                .add(ModBlocks.CRACKED_DEEPSLATE_TILES_PRESSURE_PLATE)
                //brick
                .add(ModBlocks.BRICK_DOOR)
                .add(ModBlocks.BRICK_TRAPDOOR)
                .add(ModBlocks.BRICK_FENCE_GATE)
                .add(ModBlocks.BRICK_FENCE)
                .add(ModBlocks.BRICK_BUTTON)
                .add(ModBlocks.BRICK_PRESSURE_PLATE);

        getOrCreateTagBuilder(BlockTags.AXE_MINEABLE)
                //oak
                .add(ModBlocks.OAK_WOOD_MOD)
                .add(ModBlocks.OAK_WOOD_STAIRS)
                .add(ModBlocks.OAK_WOOD_FENCE_GATE)
                .add(ModBlocks.OAK_WOOD_FENCE)
                .add(ModBlocks.OAK_WOOD_BUTTON)
                .add(ModBlocks.OAK_WOOD_DOOR)
                .add(ModBlocks.OAK_WOOD_SLAB)
                .add(ModBlocks.OAK_WOOD_PRESSURE_PLATE)
                .add(ModBlocks.OAK_WOOD_TRAPDOOR)
                //str oak
                .add(ModBlocks.STR_OAK_WOOD_STAIRS)
                .add(ModBlocks.STR_OAK_WOOD_FENCE_GATE)
                .add(ModBlocks.STR_OAK_WOOD_FENCE)
                .add(ModBlocks.STR_OAK_WOOD_BUTTON)
                .add(ModBlocks.STR_OAK_WOOD_DOOR)
                .add(ModBlocks.STR_OAK_WOOD_SLAB)
                .add(ModBlocks.STR_OAK_WOOD_PRESSURE_PLATE)
                .add(ModBlocks.STR_OAK_WOOD_TRAPDOOR)
                //spruce
                .add(ModBlocks.SPRUCE_WOOD_STAIRS)
                .add(ModBlocks.SPRUCE_WOOD_FENCE_GATE)
                .add(ModBlocks.SPRUCE_WOOD_FENCE)
                .add(ModBlocks.SPRUCE_WOOD_BUTTON)
                .add(ModBlocks.SPRUCE_WOOD_DOOR)
                .add(ModBlocks.SPRUCE_WOOD_SLAB)
                .add(ModBlocks.SPRUCE_WOOD_PRESSURE_PLATE)
                .add(ModBlocks.SPRUCE_WOOD_TRAPDOOR)
                //str spruce
                .add(ModBlocks.STR_SPRUCE_WOOD_STAIRS)
                .add(ModBlocks.STR_SPRUCE_WOOD_FENCE_GATE)
                .add(ModBlocks.STR_SPRUCE_WOOD_FENCE)
                .add(ModBlocks.STR_SPRUCE_WOOD_BUTTON)
                .add(ModBlocks.STR_SPRUCE_WOOD_DOOR)
                .add(ModBlocks.STR_SPRUCE_WOOD_SLAB)
                .add(ModBlocks.STR_SPRUCE_WOOD_PRESSURE_PLATE)
                .add(ModBlocks.STR_SPRUCE_WOOD_TRAPDOOR)
                //birch
                .add(ModBlocks.BIRCH_WOOD_STAIRS)
                .add(ModBlocks.BIRCH_WOOD_SLAB)
                .add(ModBlocks.BIRCH_WOOD_FENCE)
                .add(ModBlocks.BIRCH_WOOD_FENCE_GATE)
                .add(ModBlocks.BIRCH_WOOD_DOOR)
                .add(ModBlocks.BIRCH_WOOD_TRAPDOOR)
                .add(ModBlocks.BIRCH_WOOD_PRESSURE_PLATE)
                .add(ModBlocks.BIRCH_WOOD_BUTTON)
                //str birch
                .add(ModBlocks.STR_BIRCH_WOOD_STAIRS)
                .add(ModBlocks.STR_BIRCH_WOOD_SLAB)
                .add(ModBlocks.STR_BIRCH_WOOD_FENCE)
                .add(ModBlocks.STR_BIRCH_WOOD_FENCE_GATE)
                .add(ModBlocks.STR_BIRCH_WOOD_DOOR)
                .add(ModBlocks.STR_BIRCH_WOOD_TRAPDOOR)
                .add(ModBlocks.STR_BIRCH_WOOD_PRESSURE_PLATE)
                .add(ModBlocks.STR_BIRCH_WOOD_BUTTON)
                //jungle
                .add(ModBlocks.JUNGLE_WOOD_STAIRS)
                .add(ModBlocks.JUNGLE_WOOD_SLAB)
                .add(ModBlocks.JUNGLE_WOOD_FENCE)
                .add(ModBlocks.JUNGLE_WOOD_FENCE_GATE)
                .add(ModBlocks.JUNGLE_WOOD_DOOR)
                .add(ModBlocks.JUNGLE_WOOD_TRAPDOOR)
                .add(ModBlocks.JUNGLE_WOOD_PRESSURE_PLATE)
                .add(ModBlocks.JUNGLE_WOOD_BUTTON)
                //str jungle
                .add(ModBlocks.STR_JUNGLE_WOOD_STAIRS)
                .add(ModBlocks.STR_JUNGLE_WOOD_SLAB)
                .add(ModBlocks.STR_JUNGLE_WOOD_FENCE)
                .add(ModBlocks.STR_JUNGLE_WOOD_FENCE_GATE)
                .add(ModBlocks.STR_JUNGLE_WOOD_DOOR)
                .add(ModBlocks.STR_JUNGLE_WOOD_TRAPDOOR)
                .add(ModBlocks.STR_JUNGLE_WOOD_PRESSURE_PLATE)
                .add(ModBlocks.STR_JUNGLE_WOOD_BUTTON)
                //acacia
                .add(ModBlocks.ACACIA_WOOD_STAIRS)
                .add(ModBlocks.ACACIA_WOOD_SLAB)
                .add(ModBlocks.ACACIA_WOOD_FENCE)
                .add(ModBlocks.ACACIA_WOOD_FENCE_GATE)
                .add(ModBlocks.ACACIA_WOOD_DOOR)
                .add(ModBlocks.ACACIA_WOOD_TRAPDOOR)
                .add(ModBlocks.ACACIA_WOOD_PRESSURE_PLATE)
                .add(ModBlocks.ACACIA_WOOD_BUTTON)
                //str acacia
                .add(ModBlocks.STR_ACACIA_WOOD_STAIRS)
                .add(ModBlocks.STR_ACACIA_WOOD_SLAB)
                .add(ModBlocks.STR_ACACIA_WOOD_FENCE)
                .add(ModBlocks.STR_ACACIA_WOOD_FENCE_GATE)
                .add(ModBlocks.STR_ACACIA_WOOD_DOOR)
                .add(ModBlocks.STR_ACACIA_WOOD_TRAPDOOR)
                .add(ModBlocks.STR_ACACIA_WOOD_PRESSURE_PLATE)
                .add(ModBlocks.STR_ACACIA_WOOD_BUTTON)
                //dark oak
                .add(ModBlocks.DARK_OAK_WOOD_STAIRS)
                .add(ModBlocks.DARK_OAK_WOOD_SLAB)
                .add(ModBlocks.DARK_OAK_WOOD_FENCE)
                .add(ModBlocks.DARK_OAK_WOOD_FENCE_GATE)
                .add(ModBlocks.DARK_OAK_WOOD_DOOR)
                .add(ModBlocks.DARK_OAK_WOOD_TRAPDOOR)
                .add(ModBlocks.DARK_OAK_WOOD_PRESSURE_PLATE)
                .add(ModBlocks.DARK_OAK_WOOD_BUTTON)
                //mangrove
                .add(ModBlocks.MANGROVE_WOOD_STAIRS)
                .add(ModBlocks.MANGROVE_WOOD_SLAB)
                .add(ModBlocks.MANGROVE_WOOD_FENCE)
                .add(ModBlocks.MANGROVE_WOOD_FENCE_GATE)
                .add(ModBlocks.MANGROVE_WOOD_DOOR)
                .add(ModBlocks.MANGROVE_WOOD_TRAPDOOR)
                .add(ModBlocks.MANGROVE_WOOD_PRESSURE_PLATE)
                .add(ModBlocks.MANGROVE_WOOD_BUTTON)
                //str mangrove
                .add(ModBlocks.STR_MANGROVE_WOOD_STAIRS)
                .add(ModBlocks.STR_MANGROVE_WOOD_SLAB)
                .add(ModBlocks.STR_MANGROVE_WOOD_FENCE)
                .add(ModBlocks.STR_MANGROVE_WOOD_FENCE_GATE)
                .add(ModBlocks.STR_MANGROVE_WOOD_DOOR)
                .add(ModBlocks.STR_MANGROVE_WOOD_TRAPDOOR)
                .add(ModBlocks.STR_MANGROVE_WOOD_PRESSURE_PLATE)
                .add(ModBlocks.STR_MANGROVE_WOOD_BUTTON)
                //cherry
                .add(ModBlocks.CHERRY_WOOD_STAIRS)
                .add(ModBlocks.CHERRY_WOOD_SLAB)
                .add(ModBlocks.CHERRY_WOOD_FENCE)
                .add(ModBlocks.CHERRY_WOOD_FENCE_GATE)
                .add(ModBlocks.CHERRY_WOOD_DOOR)
                .add(ModBlocks.CHERRY_WOOD_TRAPDOOR)
                .add(ModBlocks.CHERRY_WOOD_PRESSURE_PLATE)
                .add(ModBlocks.CHERRY_WOOD_BUTTON)
                //str cherry
                .add(ModBlocks.CHERRY_WOOD_STAIRS)
                .add(ModBlocks.CHERRY_WOOD_SLAB)
                .add(ModBlocks.CHERRY_WOOD_FENCE)
                .add(ModBlocks.CHERRY_WOOD_FENCE_GATE)
                .add(ModBlocks.CHERRY_WOOD_DOOR)
                .add(ModBlocks.CHERRY_WOOD_TRAPDOOR)
                .add(ModBlocks.CHERRY_WOOD_PRESSURE_PLATE)
                .add(ModBlocks.CHERRY_WOOD_BUTTON)
                //bamboo
                .add(ModBlocks.BAMBOO_BLOCK_STAIRS)
                .add(ModBlocks.BAMBOO_BLOCK_SLAB)
                .add(ModBlocks.BAMBOO_BLOCK_FENCE)
                .add(ModBlocks.BAMBOO_BLOCK_FENCE_GATE)
                .add(ModBlocks.BAMBOO_BLOCK_DOOR)
                .add(ModBlocks.BAMBOO_BLOCK_TRAPDOOR)
                .add(ModBlocks.BAMBOO_BLOCK_PRESSURE_PLATE)
                .add(ModBlocks.BAMBOO_BLOCK_BUTTON)
                //str bamboo
                .add(ModBlocks.STR_BAMBOO_BLOCK_STAIRS)
                .add(ModBlocks.STR_BAMBOO_BLOCK_SLAB)
                .add(ModBlocks.STR_BAMBOO_BLOCK_FENCE)
                .add(ModBlocks.STR_BAMBOO_BLOCK_FENCE_GATE)
                .add(ModBlocks.STR_BAMBOO_BLOCK_DOOR)
                .add(ModBlocks.STR_BAMBOO_BLOCK_TRAPDOOR)
                .add(ModBlocks.STR_BAMBOO_BLOCK_PRESSURE_PLATE)
                .add(ModBlocks.STR_BAMBOO_BLOCK_BUTTON)
                //crimson hyphae
                .add(ModBlocks.CRIMSON_HYPHAE_STAIRS)
                .add(ModBlocks.CRIMSON_HYPHAE_SLAB)
                .add(ModBlocks.CRIMSON_HYPHAE_FENCE)
                .add(ModBlocks.CRIMSON_HYPHAE_FENCE_GATE)
                .add(ModBlocks.CRIMSON_HYPHAE_DOOR)
                .add(ModBlocks.CRIMSON_HYPHAE_TRAPDOOR)
                .add(ModBlocks.CRIMSON_HYPHAE_PRESSURE_PLATE)
                .add(ModBlocks.CRIMSON_HYPHAE_BUTTON)
                //str crimson hyphae
                .add(ModBlocks.CRIMSON_HYPHAE_STAIRS)
                .add(ModBlocks.CRIMSON_HYPHAE_SLAB)
                .add(ModBlocks.CRIMSON_HYPHAE_FENCE)
                .add(ModBlocks.CRIMSON_HYPHAE_FENCE_GATE)
                .add(ModBlocks.CRIMSON_HYPHAE_DOOR)
                .add(ModBlocks.CRIMSON_HYPHAE_TRAPDOOR)
                .add(ModBlocks.CRIMSON_HYPHAE_PRESSURE_PLATE)
                .add(ModBlocks.CRIMSON_HYPHAE_BUTTON)
                //warped hyphae
                .add(ModBlocks.WARPED_HYPHAE_STAIRS)
                .add(ModBlocks.WARPED_HYPHAE_SLAB)
                .add(ModBlocks.WARPED_HYPHAE_FENCE)
                .add(ModBlocks.WARPED_HYPHAE_FENCE_GATE)
                .add(ModBlocks.WARPED_HYPHAE_DOOR)
                .add(ModBlocks.WARPED_HYPHAE_TRAPDOOR)
                .add(ModBlocks.WARPED_HYPHAE_PRESSURE_PLATE)
                .add(ModBlocks.WARPED_HYPHAE_BUTTON)
                //str warped hyphae
                .add(ModBlocks.STR_WARPED_HYPHAE_STAIRS)
                .add(ModBlocks.STR_WARPED_HYPHAE_SLAB)
                .add(ModBlocks.STR_WARPED_HYPHAE_FENCE)
                .add(ModBlocks.STR_WARPED_HYPHAE_FENCE_GATE)
                .add(ModBlocks.STR_WARPED_HYPHAE_DOOR)
                .add(ModBlocks.STR_WARPED_HYPHAE_TRAPDOOR)
                .add(ModBlocks.STR_WARPED_HYPHAE_PRESSURE_PLATE)
                .add(ModBlocks.STR_WARPED_HYPHAE_BUTTON);

        getOrCreateTagBuilder(BlockTags.WOODEN_FENCES)
                .add(ModBlocks.OAK_WOOD_FENCE)
                .add(ModBlocks.STR_OAK_WOOD_FENCE)
                .add(ModBlocks.SPRUCE_WOOD_FENCE)
                .add(ModBlocks.STR_SPRUCE_WOOD_FENCE)
                .add(ModBlocks.BIRCH_WOOD_FENCE)
                .add(ModBlocks.STR_BIRCH_WOOD_FENCE)
                .add(ModBlocks.JUNGLE_WOOD_FENCE)
                .add(ModBlocks.STR_JUNGLE_WOOD_FENCE)
                .add(ModBlocks.ACACIA_WOOD_FENCE)
                .add(ModBlocks.STR_ACACIA_WOOD_FENCE)
                .add(ModBlocks.DARK_OAK_WOOD_FENCE)
                .add(ModBlocks.STR_DARK_OAK_WOOD_FENCE)
                .add(ModBlocks.MANGROVE_WOOD_FENCE)
                .add(ModBlocks.STR_MANGROVE_WOOD_FENCE)
                .add(ModBlocks.CHERRY_WOOD_FENCE)
                .add(ModBlocks.STR_CHERRY_WOOD_FENCE)
                .add(ModBlocks.BAMBOO_BLOCK_FENCE)
                .add(ModBlocks.STR_BAMBOO_BLOCK_FENCE)
                .add(ModBlocks.CRIMSON_HYPHAE_FENCE)
                .add(ModBlocks.STR_CRIMSON_HYPHAE_FENCE)
                .add(ModBlocks.WARPED_HYPHAE_FENCE)
                .add(ModBlocks.STR_WARPED_HYPHAE_FENCE)
                .add(ModBlocks.STONE_FENCE)
                .add(ModBlocks.COBBLESTONE_FENCE)
                .add(ModBlocks.MOSSY_COBBLESTONE_FENCE)
                .add(ModBlocks.SMOOTH_STONE_FENCE)
                .add(ModBlocks.STONE_BRICKS_FENCE)
                .add(ModBlocks.CRACKED_STONE_BRICKS_FENCE)
                .add(ModBlocks.GRANITE_FENCE)
                .add(ModBlocks.POLISHED_GRANITE_FENCE)
                .add(ModBlocks.DIORITE_FENCE)
                .add(ModBlocks.POLISHED_DIORITE_FENCE)
                .add(ModBlocks.ANDESITE_FENCE)
                .add(ModBlocks.POLISHED_ANDESITE_FENCE)
                .add(ModBlocks.DEEPSLATE_FENCE)
                .add(ModBlocks.COBBLED_DEEPSLATE_FENCE)
                .add(ModBlocks.CHISELED_DEEPSLATE_FENCE)
                .add(ModBlocks.POLISHED_DEEPSLATE_FENCE)
                .add(ModBlocks.DEEPSLATE_BRICKS_FENCE)
                .add(ModBlocks.CRACKED_DEEPSLATE_BRICKS_FENCE)
                .add(ModBlocks.DEEPSLATE_TILES_FENCE)
                .add(ModBlocks.CRACKED_DEEPSLATE_TILES_FENCE)
                .add(ModBlocks.BRICK_FENCE)
                .add(ModBlocks.PACKED_MUD_FENCE);


        getOrCreateTagBuilder(BlockTags.FENCES)
                .add(ModBlocks.OAK_WOOD_FENCE)
                .add(ModBlocks.STR_OAK_WOOD_FENCE)
                .add(ModBlocks.SPRUCE_WOOD_FENCE)
                .add(ModBlocks.STR_SPRUCE_WOOD_FENCE)
                .add(ModBlocks.BIRCH_WOOD_FENCE)
                .add(ModBlocks.STR_BIRCH_WOOD_FENCE)
                .add(ModBlocks.JUNGLE_WOOD_FENCE)
                .add(ModBlocks.STR_JUNGLE_WOOD_FENCE)
                .add(ModBlocks.ACACIA_WOOD_FENCE)
                .add(ModBlocks.STR_ACACIA_WOOD_FENCE)
                .add(ModBlocks.DARK_OAK_WOOD_FENCE)
                .add(ModBlocks.STR_DARK_OAK_WOOD_FENCE)
                .add(ModBlocks.MANGROVE_WOOD_FENCE)
                .add(ModBlocks.STR_MANGROVE_WOOD_FENCE)
                .add(ModBlocks.CHERRY_WOOD_FENCE)
                .add(ModBlocks.STR_CHERRY_WOOD_FENCE)
                .add(ModBlocks.BAMBOO_BLOCK_FENCE)
                .add(ModBlocks.STR_BAMBOO_BLOCK_FENCE)
                .add(ModBlocks.CRIMSON_HYPHAE_FENCE)
                .add(ModBlocks.STR_CRIMSON_HYPHAE_FENCE)
                .add(ModBlocks.WARPED_HYPHAE_FENCE)
                .add(ModBlocks.STR_WARPED_HYPHAE_FENCE)
                .add(ModBlocks.STONE_FENCE)
                .add(ModBlocks.COBBLESTONE_FENCE)
                .add(ModBlocks.MOSSY_COBBLESTONE_FENCE)
                .add(ModBlocks.SMOOTH_STONE_FENCE)
                .add(ModBlocks.STONE_BRICKS_FENCE)
                .add(ModBlocks.CRACKED_STONE_BRICKS_FENCE)
                .add(ModBlocks.GRANITE_FENCE)
                .add(ModBlocks.POLISHED_GRANITE_FENCE)
                .add(ModBlocks.DIORITE_FENCE)
                .add(ModBlocks.POLISHED_DIORITE_FENCE)
                .add(ModBlocks.ANDESITE_FENCE)
                .add(ModBlocks.POLISHED_ANDESITE_FENCE)
                .add(ModBlocks.DEEPSLATE_FENCE)
                .add(ModBlocks.COBBLED_DEEPSLATE_FENCE)
                .add(ModBlocks.CHISELED_DEEPSLATE_FENCE)
                .add(ModBlocks.POLISHED_DEEPSLATE_FENCE)
                .add(ModBlocks.DEEPSLATE_BRICKS_FENCE)
                .add(ModBlocks.CRACKED_DEEPSLATE_BRICKS_FENCE)
                .add(ModBlocks.DEEPSLATE_TILES_FENCE)
                .add(ModBlocks.CRACKED_DEEPSLATE_TILES_FENCE)
                .add(ModBlocks.BRICK_FENCE)
                .add(ModBlocks.PACKED_MUD_FENCE);


        getOrCreateTagBuilder(BlockTags.FENCE_GATES)
                .add(ModBlocks.OAK_WOOD_FENCE_GATE)
                .add(ModBlocks.STR_OAK_WOOD_FENCE_GATE)
                .add(ModBlocks.SPRUCE_WOOD_FENCE_GATE)
                .add(ModBlocks.STR_SPRUCE_WOOD_FENCE_GATE)
                .add(ModBlocks.BIRCH_WOOD_FENCE_GATE)
                .add(ModBlocks.STR_BIRCH_WOOD_FENCE_GATE)
                .add(ModBlocks.JUNGLE_WOOD_FENCE_GATE)
                .add(ModBlocks.STR_JUNGLE_WOOD_FENCE_GATE)
                .add(ModBlocks.ACACIA_WOOD_FENCE_GATE)
                .add(ModBlocks.STR_ACACIA_WOOD_FENCE_GATE)
                .add(ModBlocks.DARK_OAK_WOOD_FENCE_GATE)
                .add(ModBlocks.STR_DARK_OAK_WOOD_FENCE_GATE)
                .add(ModBlocks.MANGROVE_WOOD_FENCE_GATE)
                .add(ModBlocks.STR_MANGROVE_WOOD_FENCE_GATE)
                .add(ModBlocks.CHERRY_WOOD_FENCE_GATE)
                .add(ModBlocks.STR_CHERRY_WOOD_FENCE_GATE)
                .add(ModBlocks.BAMBOO_BLOCK_FENCE_GATE)
                .add(ModBlocks.STR_BAMBOO_BLOCK_FENCE_GATE)
                .add(ModBlocks.CRIMSON_HYPHAE_FENCE_GATE)
                .add(ModBlocks.STR_CRIMSON_HYPHAE_FENCE_GATE)
                .add(ModBlocks.WARPED_HYPHAE_FENCE_GATE)
                .add(ModBlocks.STR_WARPED_HYPHAE_FENCE_GATE)
                .add(ModBlocks.STONE_FENCE_GATE)
                .add(ModBlocks.COBBLESTONE_FENCE_GATE)
                .add(ModBlocks.MOSSY_COBBLESTONE_FENCE_GATE)
                .add(ModBlocks.SMOOTH_STONE_FENCE_GATE)
                .add(ModBlocks.STONE_BRICKS_FENCE_GATE)
                .add(ModBlocks.CRACKED_STONE_BRICKS_FENCE_GATE)
                .add(ModBlocks.GRANITE_FENCE_GATE)
                .add(ModBlocks.POLISHED_GRANITE_FENCE_GATE)
                .add(ModBlocks.DIORITE_FENCE_GATE)
                .add(ModBlocks.POLISHED_DIORITE_FENCE_GATE)
                .add(ModBlocks.ANDESITE_FENCE_GATE)
                .add(ModBlocks.POLISHED_ANDESITE_FENCE_GATE)
                .add(ModBlocks.DEEPSLATE_FENCE_GATE)
                .add(ModBlocks.COBBLED_DEEPSLATE_FENCE_GATE)
                .add(ModBlocks.CHISELED_DEEPSLATE_FENCE_GATE)
                .add(ModBlocks.POLISHED_DEEPSLATE_FENCE_GATE)
                .add(ModBlocks.DEEPSLATE_BRICKS_FENCE_GATE)
                .add(ModBlocks.CRACKED_DEEPSLATE_BRICKS_FENCE_GATE)
                .add(ModBlocks.DEEPSLATE_TILES_FENCE_GATE)
                .add(ModBlocks.CRACKED_DEEPSLATE_TILES_FENCE_GATE)
                .add(ModBlocks.BRICK_FENCE_GATE)
                .add(ModBlocks.PACKED_MUD_FENCE_GATE);

        getOrCreateTagBuilder(BlockTags.WALLS)
                .add(ModBlocks.STONE_WALL)
                .add(ModBlocks.SMOOTH_STONE_WALL)
                .add(ModBlocks.CRACKED_STONE_BRICKS_WALL)
                .add(ModBlocks.POLISHED_GRANITE_WALL)
                .add(ModBlocks.POLISHED_DIORITE_WALL)
                .add(ModBlocks.POLISHED_ANDESITE_WALL)
                .add(ModBlocks.DEEPSLATE_WALL)
                .add(ModBlocks.CHISELED_DEEPSLATE_WALL)
                .add(ModBlocks.CRACKED_DEEPSLATE_BRICKS_WALL)
                .add(ModBlocks.CRACKED_DEEPSLATE_TILES_WALL)
                .add(ModBlocks.PACKED_MUD_WALL);





        getOrCreateTagBuilder(BlockTags.NEEDS_IRON_TOOL);


        getOrCreateTagBuilder(TagKey.of(RegistryKeys.BLOCK, new Identifier("fabric", "needs_tool_level_4")));




    }
}
