package net.fellter.vanillablocksplus.registry;

import net.fabricmc.fabric.api.client.rendering.v1.ColorProviderRegistry;
import net.fellter.vanillablocksplus.block.ModBlocks;
import net.minecraft.client.color.world.BiomeColors;
import net.minecraft.world.biome.FoliageColors;

public class FoliageBlocksRegistry {
    public static void foliageBlocksMethod() {
        ColorProviderRegistry.BLOCK.register((state, world, pos, tintIndex) -> {
                    if (world == null || pos == null) {
                        return FoliageColors.getDefaultColor();
                    }
                    return BiomeColors.getGrassColor(world, pos);
                },
                ModBlocks.GRASS_SLAB,
                ModBlocks.GRASS_BUTTON,
                ModBlocks.GRASS_FENCE,
                ModBlocks.GRASS_STAIRS,
                ModBlocks.GRASS_WALL,
                ModBlocks.GRASS_FENCE_GATE,
                ModBlocks.GRASS_DOOR,
                ModBlocks.GRASS_TRAPDOOR,
                ModBlocks.GRASS_PRESSURE_PLATE);

        ColorProviderRegistry.BLOCK.register((state, world, pos, tintIndex) -> {
                    if (world == null || pos == null) {
                        return FoliageColors.getDefaultColor();
                    }
                    return BiomeColors.getFoliageColor(world, pos);
                },
                ModBlocks.OAK_LEAVES_SLAB,
                ModBlocks.OAK_LEAVES_BUTTON,
                ModBlocks.OAK_LEAVES_FENCE,
                ModBlocks.OAK_LEAVES_STAIRS,
                ModBlocks.OAK_LEAVES_WALL,
                ModBlocks.OAK_LEAVES_FENCE_GATE,
                ModBlocks.OAK_LEAVES_DOOR,
                ModBlocks.OAK_LEAVES_TRAPDOOR,
                ModBlocks.OAK_LEAVES_PRESSURE_PLATE,
                ModBlocks.SPRUCE_LEAVES_SLAB,
                ModBlocks.SPRUCE_LEAVES_BUTTON,
                ModBlocks.SPRUCE_LEAVES_FENCE,
                ModBlocks.SPRUCE_LEAVES_STAIRS,
                ModBlocks.SPRUCE_LEAVES_WALL,
                ModBlocks.SPRUCE_LEAVES_FENCE_GATE,
                ModBlocks.SPRUCE_LEAVES_DOOR,
                ModBlocks.SPRUCE_LEAVES_TRAPDOOR,
                ModBlocks.SPRUCE_LEAVES_PRESSURE_PLATE,
                ModBlocks.BIRCH_LEAVES_SLAB,
                ModBlocks.BIRCH_LEAVES_BUTTON,
                ModBlocks.BIRCH_LEAVES_FENCE,
                ModBlocks.BIRCH_LEAVES_STAIRS,
                ModBlocks.BIRCH_LEAVES_WALL,
                ModBlocks.BIRCH_LEAVES_FENCE_GATE,
                ModBlocks.BIRCH_LEAVES_DOOR,
                ModBlocks.BIRCH_LEAVES_TRAPDOOR,
                ModBlocks.BIRCH_LEAVES_PRESSURE_PLATE,
                ModBlocks.JUNGLE_LEAVES_SLAB,
                ModBlocks.JUNGLE_LEAVES_BUTTON,
                ModBlocks.JUNGLE_LEAVES_FENCE,
                ModBlocks.JUNGLE_LEAVES_STAIRS,
                ModBlocks.JUNGLE_LEAVES_WALL,
                ModBlocks.JUNGLE_LEAVES_FENCE_GATE,
                ModBlocks.JUNGLE_LEAVES_DOOR,
                ModBlocks.JUNGLE_LEAVES_TRAPDOOR,
                ModBlocks.JUNGLE_LEAVES_PRESSURE_PLATE,
                ModBlocks.ACACIA_LEAVES_SLAB,
                ModBlocks.ACACIA_LEAVES_BUTTON,
                ModBlocks.ACACIA_LEAVES_FENCE,
                ModBlocks.ACACIA_LEAVES_STAIRS,
                ModBlocks.ACACIA_LEAVES_WALL,
                ModBlocks.ACACIA_LEAVES_FENCE_GATE,
                ModBlocks.ACACIA_LEAVES_DOOR,
                ModBlocks.ACACIA_LEAVES_TRAPDOOR,
                ModBlocks.ACACIA_LEAVES_PRESSURE_PLATE,
                ModBlocks.DARK_OAK_LEAVES_SLAB,
                ModBlocks.DARK_OAK_LEAVES_BUTTON,
                ModBlocks.DARK_OAK_LEAVES_FENCE,
                ModBlocks.DARK_OAK_LEAVES_STAIRS,
                ModBlocks.DARK_OAK_LEAVES_WALL,
                ModBlocks.DARK_OAK_LEAVES_FENCE_GATE,
                ModBlocks.DARK_OAK_LEAVES_DOOR,
                ModBlocks.DARK_OAK_LEAVES_TRAPDOOR,
                ModBlocks.DARK_OAK_LEAVES_PRESSURE_PLATE,
                ModBlocks.MANGROVE_LEAVES_SLAB,
                ModBlocks.MANGROVE_LEAVES_BUTTON,
                ModBlocks.MANGROVE_LEAVES_FENCE,
                ModBlocks.MANGROVE_LEAVES_STAIRS,
                ModBlocks.MANGROVE_LEAVES_WALL,
                ModBlocks.MANGROVE_LEAVES_FENCE_GATE,
                ModBlocks.MANGROVE_LEAVES_DOOR,
                ModBlocks.MANGROVE_LEAVES_TRAPDOOR,
                ModBlocks.MANGROVE_LEAVES_PRESSURE_PLATE);

        ColorProviderRegistry.ITEM.register(((stack, tintIndex) -> FoliageColors.getDefaultColor()),
                ModBlocks.GRASS_SLAB,
                ModBlocks.GRASS_BUTTON,
                ModBlocks.GRASS_FENCE,
                ModBlocks.GRASS_STAIRS,
                ModBlocks.GRASS_WALL,
                ModBlocks.GRASS_FENCE_GATE,
                ModBlocks.GRASS_TRAPDOOR,
                ModBlocks.GRASS_PRESSURE_PLATE,
                ModBlocks.OAK_LEAVES_SLAB,
                ModBlocks.OAK_LEAVES_BUTTON,
                ModBlocks.OAK_LEAVES_FENCE,
                ModBlocks.OAK_LEAVES_STAIRS,
                ModBlocks.OAK_LEAVES_WALL,
                ModBlocks.OAK_LEAVES_FENCE_GATE,
                ModBlocks.OAK_LEAVES_TRAPDOOR,
                ModBlocks.OAK_LEAVES_PRESSURE_PLATE,
                ModBlocks.OAK_LEAVES_DOOR,
                ModBlocks.SPRUCE_LEAVES_SLAB,
                ModBlocks.SPRUCE_LEAVES_BUTTON,
                ModBlocks.SPRUCE_LEAVES_FENCE,
                ModBlocks.SPRUCE_LEAVES_STAIRS,
                ModBlocks.SPRUCE_LEAVES_WALL,
                ModBlocks.SPRUCE_LEAVES_FENCE_GATE,
                ModBlocks.SPRUCE_LEAVES_TRAPDOOR,
                ModBlocks.SPRUCE_LEAVES_PRESSURE_PLATE,
                ModBlocks.SPRUCE_LEAVES_DOOR,
                ModBlocks.BIRCH_LEAVES_SLAB,
                ModBlocks.BIRCH_LEAVES_BUTTON,
                ModBlocks.BIRCH_LEAVES_FENCE,
                ModBlocks.BIRCH_LEAVES_STAIRS,
                ModBlocks.BIRCH_LEAVES_WALL,
                ModBlocks.BIRCH_LEAVES_FENCE_GATE,
                ModBlocks.BIRCH_LEAVES_TRAPDOOR,
                ModBlocks.BIRCH_LEAVES_PRESSURE_PLATE,
                ModBlocks.BIRCH_LEAVES_DOOR,
                ModBlocks.JUNGLE_LEAVES_SLAB,
                ModBlocks.JUNGLE_LEAVES_BUTTON,
                ModBlocks.JUNGLE_LEAVES_FENCE,
                ModBlocks.JUNGLE_LEAVES_STAIRS,
                ModBlocks.JUNGLE_LEAVES_WALL,
                ModBlocks.JUNGLE_LEAVES_FENCE_GATE,
                ModBlocks.JUNGLE_LEAVES_TRAPDOOR,
                ModBlocks.JUNGLE_LEAVES_PRESSURE_PLATE,
                ModBlocks.JUNGLE_LEAVES_DOOR,
                ModBlocks.ACACIA_LEAVES_SLAB,
                ModBlocks.ACACIA_LEAVES_BUTTON,
                ModBlocks.ACACIA_LEAVES_FENCE,
                ModBlocks.ACACIA_LEAVES_STAIRS,
                ModBlocks.ACACIA_LEAVES_WALL,
                ModBlocks.ACACIA_LEAVES_FENCE_GATE,
                ModBlocks.ACACIA_LEAVES_TRAPDOOR,
                ModBlocks.ACACIA_LEAVES_PRESSURE_PLATE,
                ModBlocks.ACACIA_LEAVES_DOOR,
                ModBlocks.DARK_OAK_LEAVES_SLAB,
                ModBlocks.DARK_OAK_LEAVES_BUTTON,
                ModBlocks.DARK_OAK_LEAVES_FENCE,
                ModBlocks.DARK_OAK_LEAVES_STAIRS,
                ModBlocks.DARK_OAK_LEAVES_WALL,
                ModBlocks.DARK_OAK_LEAVES_FENCE_GATE,
                ModBlocks.DARK_OAK_LEAVES_TRAPDOOR,
                ModBlocks.DARK_OAK_LEAVES_PRESSURE_PLATE,
                ModBlocks.DARK_OAK_LEAVES_DOOR,
                ModBlocks.MANGROVE_LEAVES_SLAB,
                ModBlocks.MANGROVE_LEAVES_BUTTON,
                ModBlocks.MANGROVE_LEAVES_FENCE,
                ModBlocks.MANGROVE_LEAVES_STAIRS,
                ModBlocks.MANGROVE_LEAVES_WALL,
                ModBlocks.MANGROVE_LEAVES_FENCE_GATE,
                ModBlocks.MANGROVE_LEAVES_TRAPDOOR,
                ModBlocks.MANGROVE_LEAVES_PRESSURE_PLATE,
                ModBlocks.MANGROVE_LEAVES_DOOR);

    }
}
